# Generated by Django 4.2 on 2025-08-07 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0009_project_created_at"),
        ("logs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField()),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "celery_task_log",
                    models.ForeignKey(
                        blank=True,
                        help_text="Celery task log associated with this project report",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="logs.celerytasklog",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_report",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-creation_date"],
            },
        ),
    ]
