# Generated by Django 3.2.7 on 2021-12-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='enable_public_page',
            field=models.BooleanField(default=False, help_text='Will enable the public page to share current project status', verbose_name='Enable public page'),
        ),
    ]
