# Generated by Django 4.1.5 on 2023-01-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Favorite project are highlighted and first shown when possible.', verbose_name='Is favorite'),
        ),
    ]
