# Generated by Django 4.1.5 on 2023-01-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='enable_badges',
            field=models.BooleanField(default=False, help_text='Will enable the badge to embed within third party applications', verbose_name='Enable badges'),
        ),
    ]
