# Generated by Django 4.1.5 on 2023-01-24 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alter_instancedownincident_service'),
        ('projects', '0006_remove_project_enable_badges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='httpmockedcodeservice',
            name='service',
        ),
        migrations.RemoveField(
            model_name='service',
            name='project',
        ),
        migrations.DeleteModel(
            name='HTTPCodeService',
        ),
        migrations.DeleteModel(
            name='HTTPMockedCodeService',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
