# Generated by Django 5.1.3 on 2024-11-27 06:17

import django.db.models.deletion
import performances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lighthouse',
            fields=[
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='lighthouse', serialize=False, to='projects.pages')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('request_run', models.BooleanField(default=False, help_text='Request a run')),
                ('last_request_date', models.DateTimeField(blank=True, help_text='Last request date', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.ImageField(blank=True, help_text='Lighthouse screenshot', null=True, upload_to=performances.models.user_directory_path)),
                ('form_factor', models.IntegerField(choices=[(0, 'Desktop'), (1, 'Mobile')], default=0, help_text='Lighthouse form factor, mobile or desktop')),
                ('score_performance', models.FloatField(blank=True, help_text='Lighthouse performance score', null=True)),
                ('score_accessibility', models.FloatField(blank=True, help_text='Lighthouse accessibility score', null=True)),
                ('score_best_practices', models.FloatField(blank=True, help_text='Lighthouse best practices score', null=True)),
                ('score_seo', models.FloatField(blank=True, help_text='Lighthouse seo score', null=True)),
                ('score_pwa', models.FloatField(blank=True, help_text='Lighthouse pwa score', null=True)),
                ('report_json_file', models.FileField(blank=True, help_text='Lighthouse report', null=True, upload_to=performances.models.user_directory_path)),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='performances.lighthouse')),
            ],
        ),
    ]
