# Generated by Django 4.2 on 2024-10-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='performance',
            constraint=models.UniqueConstraint(fields=('id', 'url'), name='unique_id_url'),
        ),
    ]
