# Generated by Django 4.2 on 2024-10-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0002_performance_unique_id_url'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='performance',
            name='unique_id_url',
        ),
        migrations.AddConstraint(
            model_name='performance',
            constraint=models.UniqueConstraint(fields=('project', 'url'), name='unique_project_url'),
        ),
    ]
