# Generated by Django 3.2.7 on 2021-11-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert', models.CharField(max_length=128)),
                ('expr', models.CharField(max_length=128)),
                ('duration', models.CharField(max_length=8)),
                ('severity', models.IntegerField(choices=[(0, 'unknown'), (1, 'warning'), (2, 'critical')])),
                ('summary', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
