# Generated by Django 3.2.7 on 2022-01-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_authbasic'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='port',
            field=models.IntegerField(default=8001),
        ),
        migrations.AddField(
            model_name='server',
            name='url',
            field=models.CharField(default='host.docker.internal', max_length=256),
        ),
    ]
