# Generated by Django 4.1.5 on 2023-01-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20220111_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='port',
        ),
        migrations.AlterField(
            model_name='server',
            name='url',
            field=models.CharField(max_length=256),
        ),
    ]
