# Generated by Django 4.1.5 on 2023-08-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alerts',
            options={'verbose_name': 'Alert', 'verbose_name_plural': 'Alerts'},
        ),
        migrations.RemoveField(
            model_name='alerts',
            name='alert',
        ),
        migrations.AddField(
            model_name='alerts',
            name='name',
            field=models.CharField(default='Unknown', help_text='Alert name', max_length=128),
            preserve_default=False,
        ),
    ]
