# Generated by Django 4.1.5 on 2023-01-24 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0001_initial'),
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancedownincident',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instancedownincidents', to='availability.service'),
        ),
    ]
