# Generated by Django 4.1.5 on 2023-08-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alerts_critical_duration_alerts_warning_duration_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alerts',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='name',
            field=models.CharField(help_text='Alert name', max_length=128, unique=True),
        ),
        migrations.RemoveField(
            model_name='alerts',
            name='severity',
        ),
    ]
