# Generated by Django 4.1.5 on 2023-08-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_alter_alerts_unique_together_alter_alerts_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alerts',
            old_name='expr',
            new_name='critical_expr',
        ),
        migrations.AddField(
            model_name='alerts',
            name='warning_expr',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
