# Generated by Django 4.1.5 on 2023-08-16 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_rename_expr_alerts_critical_expr_alerts_warning_expr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerts',
            name='critical_duration',
        ),
        migrations.RemoveField(
            model_name='alerts',
            name='critical_expr',
        ),
        migrations.RemoveField(
            model_name='alerts',
            name='description',
        ),
        migrations.RemoveField(
            model_name='alerts',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='alerts',
            name='warning_duration',
        ),
        migrations.RemoveField(
            model_name='alerts',
            name='warning_expr',
        ),
        migrations.CreateModel(
            name='AlertsWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_expr', models.CharField(max_length=128)),
                ('warning_duration', models.CharField(default='2m', max_length=8)),
                ('summary', models.TextField()),
                ('description', models.TextField()),
                ('alert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warning', to='alerts.alerts')),
            ],
            options={
                'verbose_name': 'Warning',
                'verbose_name_plural': 'Warnings',
            },
        ),
        migrations.CreateModel(
            name='AlertsCritical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critical_expr', models.CharField(max_length=128)),
                ('critical_duration', models.CharField(default='5m', max_length=8)),
                ('summary', models.TextField()),
                ('description', models.TextField()),
                ('alert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='critical', to='alerts.alerts')),
            ],
            options={
                'verbose_name': 'Critical',
                'verbose_name_plural': 'Criticals',
            },
        ),
    ]
