# Generated by Django 4.1.5 on 2023-08-16 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_remove_alerts_critical_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alertscritical',
            old_name='critical_duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='alertscritical',
            old_name='critical_expr',
            new_name='expr',
        ),
        migrations.RenameField(
            model_name='alertswarning',
            old_name='warning_duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='alertswarning',
            old_name='warning_expr',
            new_name='expr',
        ),
    ]
