# Generated by Django 4.1.5 on 2023-08-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0007_rename_critical_duration_alertscritical_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='is_critical',
            field=models.BooleanField(default=False, help_text='Trigger an outrage when critical alert is triggered'),
        ),
    ]
