# Generated by Django 4.1.5 on 2023-08-21 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_user'),
        ('alerts', '0008_alerts_is_critical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disablealerts',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disable_alert', to='alerts.alerts'),
        ),
        migrations.AlterField(
            model_name='disablealerts',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disable_alerts', to='projects.project'),
        ),
    ]
