# Generated by Django 5.1.2 on 2024-10-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_profile_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='disable_auto_redirect',
            field=models.BooleanField(default=False, help_text='Disable auto-redirect from homepage to dashboard'),
        ),
    ]
