# Generated by Django 3.2.7 on 2021-10-06 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20210928_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notify_Pager_Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routing_key', models.CharField(max_length=32)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pager_duty', to='applications.application')),
            ],
        ),
    ]
