# Generated by Django 3.2.7 on 2021-10-06 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_notify_pager_duty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notify_Pager_Duty',
        ),
    ]
