global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

rule_files:
- /etc/prometheus/alerts/*.yml

alerting:
  alertmanagers:
  - scheme: http
    timeout: 10s
    path_prefix: /alertmanager
    api_version: v1
    basic_auth:
      username: {{ settings.WEBAUTH_USERNAME }}
      password: {{ settings.WEBAUTH_PASSWORD }}
    static_configs:
    - targets:
      - {{ settings.DOMAIN }}:{{ settings.PORT }}

scrape_configs:
- job_name: prometheus_metrics
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090

- job_name: alertmanager_metrics
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /alertmanager/metrics
  scheme: http
  basic_auth:
    username: {{ settings.WEBAUTH_USERNAME }}
    password: {{ settings.WEBAUTH_PASSWORD }}
  static_configs:
  - targets:
    - {{ settings.DOMAIN }}:{{ settings.PORT }}

- job_name: server_metrics
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 5s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - fr-1.sebastienbarbier.com:9100
    - fr-2.sebastienbarbier.com:9100
    - ca-1.sebastienbarbier.com:9100

- job_name: is_service_down
  metrics_path: /probe
  scrape_interval: 1m
  params:
    module:
    - http_2xx
  static_configs:
  {% for user in users %}{% if user.healthTest.all.0 %}
  - labels:
      user: {{ user }}
    targets:
    - {{ settings.DOMAIN }}:{{ settings.PORT }}/healthy/{{ user.healthTest.all.0.id }}{% endif %}
    {% for application in user.applications.all %}
  - labels:
      user: {{ user }}
      application: {{ application }}
    targets:
    {% for service in application.services.all %}- {{ service.url }}
    {% endfor %}{% endfor %}{% endfor %}
  relabel_configs:
  - source_labels:
    - __address__
    target_label: __param_target
  - source_labels:
    - __param_target
    target_label: instance
  - target_label: __address__
    replacement: blackbox:9115
