# Generated by Django 4.2 on 2025-07-10 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0003_auto_20250709_2012"),
    ]

    operations = [
        migrations.CreateModel(
            name="CeleryTaskLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=255)),
                ("duration", models.DurationField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project associated with this Celery task log",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="celery_task_logs",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "celery_task_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
