services:
  django:
    command: "gunicorn -b 0.0.0.0:8000 monitor.wsgi"
  nginx:
    volumes:
      - ./nginx/geolite/GeoLite2-Country.mmdb:/etc/GeoLite2-Country.mmdb
      - ./nginx/geolite/GeoLite2-City.mmdb:/etc/GeoLite2-City.mmdb
      - ./nginx/conf/nginx.production.conf:/etc/nginx/nginx.conf
  promtail:
    container_name: monitor_promtail
    image: grafana/promtail:2.3.0
    volumes:
      - ./data/log:/var/log
      - ./promtail/promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
  certbot:
    container_name: monitor_certbot
    image: certbot/certbot
    volumes:  
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"