version: "3.9"  # optional since v1.27.0

services:
  sphinx:
    container_name: monitor_sphinx
    build: ./sphinx
    command: "sphinx-reload /docs"
    profiles:
      - dev
    volumes:
      - ./docs:/docs
      - ./sphinx/requirements.txt:/requirements.txt
    ports:
      - "5500:5500"

volumes:
  logvolume01: {}
