version: "3.9"  # optional since v1.27.0
services:
  nginx:
    image: "nginx:latest"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/log:/var/log
      - ./data/log/nginx:/var/log/nginx
      - ./nginx/local/:/etc/nginx/conf.d/
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./.htpasswd:/etc/nginx/.htpasswd:ro
    links:
      - alertmanager
      - grafana
      - loki
      - django
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    volumes:  
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  grafana:
    image: grafana/grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-worldmap-panel 0.3.2
    links:
      - loki
    user: root
    volumes:
      - ./data/log:/var/log
      - ./data/grafana:/var/lib/grafana

  alertmanager:
    image: quay.io/prometheus/alertmanager
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
  django:
    build: ./django
    env_file:
     - ./django/monitor/.env
volumes:
  logvolume01: {}
