version: '3.8'

services:
  fromedwin_celery:
    container_name: fromedwin_celery
    build: 
      context: .
      dockerfile: ./Dockerfile
    environment:
      CELERY_BROKER_URL: ${CELERY_BROKER_URL-amqp://admin:admin@host.docker.internal}
      SECRET_KEY: ${SECRET_KEY} # Use to authenticate worker queries
      BACKEND_URL: ${BACKEND_URL-http://host.docker.internal:8000}
    volumes:
      - .:/app
    ports:
      - "8011:8000"
    entrypoint: ["/app/worker/celery/entrypoint.sh"]
  fromedwin_lighthouse:
    build: ./worker/lighthouse
    user: root
    deploy:
      replicas: ${LIGHTHOUSE_WORKER_REPLICA-1}
    volumes:
      - .:/etc/monitor
    environment:
      CELERY_BROKER_URL: ${CELERY_BROKER_URL-amqp://admin:admin@host.docker.internal}
      BACKEND_URL: ${SERVER_URL-http://host.docker.internal:8000}
      CHROME_PATH: /usr/lib/chromium/chrome
      SECRET_KEY: ${SECRET_KEY} # Use to authenticate worker queries
    command: ['sh', '/etc/monitor/worker/lighthouse/entrypoint.sh']
