version: '3.8'

services:
  fromedwin_scheduler:
    container_name: fromedwin_scheduler
    build: 
      context: .
      dockerfile: ./Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL-amqp://admin:admin@host.docker.internal}
    volumes:
      - .:/app
    ports:
      - "8010:8000"
    entrypoint: ["/app/scheduler/entrypoint.sh"]
