version: "3.9"  # optional since v1.27.0
services:
  nginx:
    image: "nginx:latest"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/log:/var/log
      - ./nginx/local/:/etc/nginx/conf.d/
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    links:
      - grafana
      - django
      - loki
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    volumes:  
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  prometheus:
    image: prom/prometheus
    volumes:
      - ./data/prometheus:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/prometheus_rules.yml:/etc/prometheus/prometheus_rules.yml:ro
    links:
      - blackbox
      - alertmanager
      - django
    user: "65534"
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-worldmap-panel 0.3.2
    # ports:
    #   - 3000:3000
    links:
      - prometheus
      - loki
    volumes:
      - ./data/log:/var/log
      - ./data/grafana:/var/lib/grafana
    user: "65534"
  blackbox:
    image: prom/blackbox-exporter:master
    user: "65534"
  loki:
    image: grafana/loki:2.0.0
    # ports:
    #   - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml:ro
  alertmanager:
    image: quay.io/prometheus/alertmanager
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
  django:
    build: ./django
    # ports:
    #   - 8000:8000
  promtail:
    image: grafana/promtail:1.6.0
    volumes:
      - ./data/log:/var/log
      - ./promtail/promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
volumes:
  logvolume01: {}
