version: '3.8'

services:
  fromedwin_scheduler:
    build: 
      context: .
      dockerfile: ./Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      STORAGE: ${STORAGE}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_S3_CUSTOM_DOMAIN: ${AWS_S3_CUSTOM_DOMAIN}
      AWS_S3_ENDPOINT_URL: ${AWS_S3_ENDPOINT_URL}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_STORAGE_BUCKET_NAME: ${AWS_STORAGE_BUCKET_NAME}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
    volumes:
      - .:/app
    ports:
      - "8010:8000"
    entrypoint: ["/app/scheduler/entrypoint.sh"]
