version: '3.8'

services:
  fromedwin_worker:
    build: 
      context: .
      dockerfile: ./Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      STORAGE: ${STORAGE}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_S3_CUSTOM_DOMAIN: ${AWS_S3_CUSTOM_DOMAIN}
      AWS_S3_ENDPOINT_URL: ${AWS_S3_ENDPOINT_URL}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_STORAGE_BUCKET_NAME: ${AWS_STORAGE_BUCKET_NAME}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL-amqp://admin:admin@host.docker.internal}
      SECRET_KEY: ${SECRET_KEY} # Use to authenticate worker queries
    volumes:
      - .:/app
    ports:
      - "8011:8000"
    entrypoint: ["/app/worker/entrypoint.sh"]
