version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    privileged: true
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER-}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS-}
    ports:
      - "5672:5672"   # RabbitMQ
      - "15672:15672" # RabbitMQ Management UI
      - "15692:15692" # Prometheus metrics endpoint (default for rabbitmq_prometheus)
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq  # Optional: persistent data storage
    command: >
      sh -c "rabbitmq-plugins enable rabbitmq_prometheus &&
             rabbitmq-plugins enable rabbitmq_management &&
             rabbitmq-server"
