# Generated by Django 3.1.4 on 2021-08-30 16:15

from django.db import migrations, models
import yamlfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertsConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('yaml', yamlfield.fields.YAMLField()),
            ],
        ),
        migrations.CreateModel(
            name='PrometheusConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('yaml', yamlfield.fields.YAMLField()),
            ],
        ),
    ]
