# Generated by Django 3.2.7 on 2021-11-24 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alerts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlertsConfig',
        ),
    ]
