# Generated by Django 3.2.7 on 2021-09-27 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_server_last_modified_setup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrometheusConfig',
        ),
    ]
