# Generated by Django 3.2.7 on 2021-10-06 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pager_duty',
            options={'verbose_name': 'Pager Duty key', 'verbose_name_plural': 'Pager Duty keys'},
        ),
    ]
