# No version needed in modern Docker Compose

name: fromedwin

services:
  #
  # Run prometheus to fetch metrics from workers and alertmanager to send alerts
  #
  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: fromedwin-prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring
    labels:
      - "coolify.managed=true"
      - "coolify.type=database"
      - "coolify.expose=true"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus/data"
      - "--web.enable-lifecycle" # Enable /-/reload entrypoint
    volumes:
      - ../data/prometheus:/prometheus
      - ../worker/prometheus/alerts:/etc/prometheus/alerts
      - ../worker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    links:
      - blackbox

  #
  # Run alertmanager to send alerts
  #
  alertmanager:
    image: quay.io/prometheus/alertmanager:v0.27.0
    container_name: fromedwin-alertmanager
    networks:
      - monitoring
    labels:
      - "coolify.managed=true"
      - "coolify.type=database"
      - "coolify.expose=true"
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--storage.path=/alertmanager/data"
    volumes:
      - ../data/alertmanager:/alertmanager
      - ../worker/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
  #
  # Run blackbox to fetch metrics from workers and alertmanager to send alerts
  #
  blackbox:
    image: prom/blackbox-exporter:v0.25.0
    container_name: fromedwin-blackbox
    networks:
      - monitoring
    labels:
      - "coolify.managed=true"
      - "coolify.type=database"
      - "coolify.expose=true"
    command:
      - "--config.file=/etc/prometheus/blackbox.yml"
    # user: "65534"
    volumes:
      - ../worker/blackbox/blackbox.yml:/etc/prometheus/blackbox.yml:ro

  #
  # Telegraf read prometheus metrics and store them in InfluxDB
  #
  telegraf:
    build:
      context: ..
      dockerfile: worker/telegraf/Dockerfile
    container_name: fromedwin-telegraf
    networks:
      - monitoring
    environment:
      - INFLUXDB_URL=${INFLUXDB_URL-http://influxdb:8086}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_BUCKET=fromedwin
      - INFLUXDB_ORG=fromedwin
      - TELEGRAF_INTERVAL=${TELEGRAF_INTERVAL-15s}
      - CELERY_BROKER_UI_URL=${CELERY_BROKER_UI_URL-http://rabbitmq:15692}
    ports:
      - "9273:9273" # Expose Telegraf Prometheus plugin metrics

  heartbeats:
    build:
      context: ..
      dockerfile: worker/heartbeats/Dockerfile
    container_name: fromedwin-heartbeats
    networks:
      - monitoring
    volumes:
      - ../worker:/etc/fromedwin_heartbeats/worker
      - ../worker/heartbeats/requirements.txt:/etc/fromedwin_heartbeats/worker/heartbeats/requirements.txt:ro
    environment:
      BACKEND_URL: ${BACKEND_URL-http://host.docker.internal:8000}
      SECRET_KEY: ${SECRET_KEY} # Use to authenticate worker queries
    command:
      ["python3", "/etc/fromedwin_heartbeats/worker/heartbeats/heartbeats.py"]

networks:
  monitoring:
    driver: bridge
