# Generated by Django 4.2 on 2025-07-09 20:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import favicons.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0002_alter_pages_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="Favicon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        help_text="Application's favicon",
                        null=True,
                        upload_to=favicons.models.favicon_upload_path,
                    ),
                ),
                (
                    "task_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Success"),
                            ("FAILURE", "Failure"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        help_text="Favicon task status",
                        max_length=16,
                    ),
                ),
                (
                    "last_edited",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Last time favicon was edited",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        help_text="Project this favicon belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favicon_details",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Favicon",
                "verbose_name_plural": "Favicons",
            },
        ),
    ]
