# Generated by Django 4.2 on 2025-07-09 20:12

from django.db import migrations


def migrate_favicon_data(apps, schema_editor):
    """
    Move favicon data from Project model to new Favicon model
    """
    Project = apps.get_model('projects', 'Project')
    Favicon = apps.get_model('favicons', 'Favicon')
    
    # Create Favicon records for all projects that have favicon data
    for project in Project.objects.all():
        # Check if the project has any favicon-related data
        if project.favicon or project.favicon_task_status != 'UNKNOWN' or project.favicon_last_edited:
            Favicon.objects.create(
                project=project,
                favicon=project.favicon,
                task_status=project.favicon_task_status,
                last_edited=project.favicon_last_edited
            )


def reverse_migrate_favicon_data(apps, schema_editor):
    """
    Reverse migration - this would be complex since we're removing fields
    For now, we'll just delete the favicon records
    """
    Favicon = apps.get_model('favicons', 'Favicon')
    Favicon.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("favicons", "0001_initial"),
        ("projects", "0002_alter_pages_project"),  # Ensure Project model is available
    ]

    operations = [
        migrations.RunPython(migrate_favicon_data, reverse_migrate_favicon_data),
    ]
