# Generated by Django 4.2 on 2025-07-10 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0001_initial"),
        ("favicons", "0002_auto_20250709_2012"),
    ]

    operations = [
        migrations.AddField(
            model_name="favicon",
            name="celery_task_log",
            field=models.ForeignKey(
                blank=True,
                help_text="Celery task log associated with this favicon (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="favicons",
                to="logs.celerytasklog",
            ),
        ),
    ]
