# Generated by Django 5.1.3 on 2024-11-27 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('availability', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_name', models.CharField(help_text='Alert name', max_length=128)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'unknown'), (1, 'resolved'), (2, 'firing')])),
                ('severity', models.IntegerField(choices=[(0, 'unknown'), (1, 'warning'), (2, 'critical')])),
                ('summary', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('json', models.TextField(help_text='RAW json as received by the webhook')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='availability.service')),
            ],
        ),
    ]
