# Generated by Django 4.1.5 on 2023-09-05 20:00

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(choices_display='STANDARD', null=True),
        ),
    ]
