# Generated by Django 4.1.5 on 2023-08-16 09:56

from django.db import migrations, models
import django.db.models.deletion
import performances.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Should start with http:// or https://', max_length=512)),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('request_run', models.BooleanField(default=False, help_text='Request a run')),
                ('last_request_date', models.DateTimeField(blank=True, help_text='Last request date', null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.ImageField(blank=True, help_text='Lighthouse screenshot', null=True, upload_to=performances.models.user_directory_path)),
                ('form_factor', models.IntegerField(choices=[(0, 'Desktop'), (1, 'Mobile')], default=0, help_text='Lighthouse form factor')),
                ('score_performance', models.FloatField(blank=True, help_text='Lighthouse performance score', null=True)),
                ('score_accessibility', models.FloatField(blank=True, help_text='Lighthouse accessibility score', null=True)),
                ('score_best_practices', models.FloatField(blank=True, help_text='Lighthouse best practices score', null=True)),
                ('score_seo', models.FloatField(blank=True, help_text='Lighthouse seo score', null=True)),
                ('score_pwa', models.FloatField(blank=True, help_text='Lighthouse pwa score', null=True)),
                ('report_json_file', models.FileField(blank=True, help_text='Lighthouse report', null=True, upload_to=performances.models.user_directory_path)),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='performances.performance')),
            ],
        ),
        migrations.CreateModel(
            name='ReportScreenshots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.ImageField(blank=True, help_text='Lighthouse screenshot', null=True, upload_to='lighthouse_screenshots')),
                ('timestamp', models.DateTimeField(blank=True, help_text='Screenshot', null=True)),
                ('timing', models.IntegerField(blank=True, help_text='Lighthouse timing', null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='performances.report')),
            ],
        ),
    ]
