# Generated by Django 4.1.5 on 2023-01-24 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0007_remove_httpmockedcodeservice_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Web page to test at regular intervals', max_length=512)),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='projects.project')),
            ],
        ),
    ]
