# Generated by Django 4.1.5 on 2023-08-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='form_factor',
            field=models.IntegerField(choices=[(0, 'Desktop'), (1, 'Mobile')], default=0, help_text='Lighthouse form factor, mobile or desktop'),
        ),
    ]
