# Generated by Django 4.1.5 on 2023-01-26 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='last_request_date',
            field=models.DateTimeField(blank=True, editable=False, help_text='Last request date', null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='url',
            field=models.URLField(help_text='Should start with http:// or https://', max_length=512),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('lighthouse_report', models.JSONField(editable=False)),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='performances.performance')),
            ],
        ),
    ]
