# Generated by Django 4.1.5 on 2023-01-30 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0003_report_lighthouse_formfactor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='lighthouse_formFactor',
            new_name='form_factor',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='lighthouse_score_accessibility',
            new_name='score_accessibility',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='lighthouse_score_bestPractices',
            new_name='score_best_practices',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='lighthouse_score_performance',
            new_name='score_performance',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='lighthouse_score_pwa',
            new_name='score_pwa',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='lighthouse_score_seo',
            new_name='score_seo',
        ),
        migrations.RemoveField(
            model_name='report',
            name='lighthouse_report',
        ),
        migrations.AddField(
            model_name='report',
            name='report_json_file',
            field=models.FileField(blank=True, help_text='Lighthouse report', null=True, upload_to='lighthouse_reports'),
        ),
        migrations.AddField(
            model_name='report',
            name='screenshot',
            field=models.ImageField(blank=True, help_text='Lighthouse screenshot', null=True, upload_to='lighthouse_screenshots'),
        ),
        migrations.CreateModel(
            name='ReportScreenshots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.ImageField(blank=True, help_text='Lighthouse screenshot', null=True, upload_to='lighthouse_screenshots')),
                ('timestamp', models.DateTimeField(blank=True, help_text='Screenshot', null=True)),
                ('timing', models.IntegerField(blank=True, help_text='Lighthouse timing', null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='performances.report')),
            ],
        ),
    ]
