# Generated by Django 4.1.5 on 2023-02-23 15:51

from django.db import migrations, models
import performances.models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0005_alter_report_score_accessibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='request_run',
            field=models.BooleanField(default=False, help_text='Request a run'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_json_file',
            field=models.FileField(blank=True, help_text='Lighthouse report', null=True, upload_to=performances.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='report',
            name='screenshot',
            field=models.ImageField(blank=True, help_text='Lighthouse screenshot', null=True, upload_to=performances.models.user_directory_path),
        ),
    ]
