# Generated by Django 4.2 on 2025-07-13 11:24

from django.db import migrations, models
import django.db.models.deletion
import lighthouse.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0004_pages_lighthouse_last_request"),
    ]

    operations = [
        migrations.CreateModel(
            name="LighthouseReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "screenshot",
                    models.ImageField(
                        blank=True,
                        help_text="Lighthouse screenshot",
                        null=True,
                        upload_to=lighthouse.models.user_directory_path,
                    ),
                ),
                (
                    "form_factor",
                    models.IntegerField(
                        choices=[(0, "Desktop"), (1, "Mobile")],
                        default=0,
                        help_text="Lighthouse form factor, mobile or desktop",
                    ),
                ),
                (
                    "score_performance",
                    models.FloatField(
                        blank=True, help_text="Lighthouse performance score", null=True
                    ),
                ),
                (
                    "score_accessibility",
                    models.FloatField(
                        blank=True,
                        help_text="Lighthouse accessibility score",
                        null=True,
                    ),
                ),
                (
                    "score_best_practices",
                    models.FloatField(
                        blank=True,
                        help_text="Lighthouse best practices score",
                        null=True,
                    ),
                ),
                (
                    "score_seo",
                    models.FloatField(
                        blank=True, help_text="Lighthouse seo score", null=True
                    ),
                ),
                (
                    "score_pwa",
                    models.FloatField(
                        blank=True, help_text="Lighthouse pwa score", null=True
                    ),
                ),
                (
                    "report_json_file",
                    models.FileField(
                        blank=True,
                        help_text="Lighthouse report",
                        null=True,
                        upload_to=lighthouse.models.user_directory_path,
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(auto_now_add=True, help_text="Creation date"),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lighthouse_report",
                        to="projects.pages",
                    ),
                ),
            ],
        ),
    ]
