# Generated by Django 4.2 on 2025-07-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lighthouse", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lighthousereport",
            name="duration",
            field=models.IntegerField(
                blank=True, help_text="Lighthouse duration", null=True
            ),
        ),
    ]
