# Generated by Django 4.2 on 2025-07-18 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0001_initial"),
        ("lighthouse", "0002_lighthousereport_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lighthousereport",
            name="duration",
        ),
        migrations.AddField(
            model_name="lighthousereport",
            name="celery_task_log",
            field=models.ForeignKey(
                blank=True,
                help_text="Celery task log associated with this lighthouse report",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lighthouse",
                to="logs.celerytasklog",
            ),
        ),
    ]
