# Generated by Django 4.2 on 2025-07-20 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lighthouse", "0003_remove_lighthousereport_duration_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lighthousereport",
            options={"ordering": ["-creation_date"]},
        ),
    ]
