{% load remove_protocol %}
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

rule_files:
- /etc/prometheus/alerts/*.yml

alerting:
  alertmanagers:
  - scheme: http
    timeout: 10s
    api_version: v1
    {% if server.authbasic.all %}basic_auth:
      username: {{ server.authbasic.all.0.username }}
      password: {{ server.authbasic.all.0.password }}{% endif %}
    static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:

# Prometheus metrics
- job_name: prometheus_metrics
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090

# Alertmanager metrics
- job_name: alertmanager_metrics
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  {% if server.authbasic.all %}basic_auth:
    username: {{ server.authbasic.all.0.username }}
    password: {{ server.authbasic.all.0.password }}{% endif %}
  static_configs:
  - targets:
    - alertmanager:9093
{% if metrics %}
- job_name: metrics
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 5s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    {% for metric in metrics %}- {{ metric.url|remove_protocol }}
    {% endfor %}{% endif %}
    
# Parse http probe for service WITH TLS SECURE VERIFICATION
- job_name: is_service_down
  metrics_path: /probe
  scrape_interval: {{ settings.IS_SERVICE_DOWN_SCRAPE_INTERVAL_SECONDS }}s
  params:
    module:
    - http_2xx
  static_configs:
  {% for user in users %}{% for project in user.projects.all %}{% for service in project.services.all %}{% if service.is_enabled and service.httpcode and not service.httpcode.tls_skip_verify %}
  - labels:
      service: {{ service.id }}
      project: {{ project.id }}
      user: {{ user.id }}
    targets:
    - {{ service.httpcode.url }}
    {% endif %}{% if service.is_enabled and service.httpmockedcode %}
  - labels:
      service: {{ service.id }}
      project: {{ project.id }}
      user: {{ user.id }}
    targets:
    - {{ service.httpmockedcode.url }}
    {% endif %}{% endfor %}{% endfor %}{% endfor %}
  relabel_configs:
  - source_labels:
    - __address__
    target_label: __param_target
  - source_labels:
    - __param_target
    target_label: instance
  - target_label: __address__
    replacement: blackbox:9115

# Parse http probe for service WITHOUT TLS SECURE VERIFICATION
- job_name: is_service_down_and_insecure
  metrics_path: /probe
  scrape_interval: {{ settings.IS_SERVICE_DOWN_SCRAPE_INTERVAL_SECONDS }}s
  params:
    module:
    - http_2xx_unsecure
  static_configs:
  {% for user in users %}{% for project in user.projects.all %}{% for service in project.services.all %}{% if service.is_enabled and service.httpcode and service.httpcode.tls_skip_verify %}
  - labels:
      service: {{ service.id }}
      project: {{ project.id }}
      user: {{ user.id }}
    targets:
    - {{ service.httpcode.url }}
    {% endif %}{% endfor %}{% endfor %}{% endfor %}
  relabel_configs:
  - source_labels:
    - __address__
    target_label: __param_target
  - source_labels:
    - __param_target
    target_label: instance
  - target_label: __address__
    replacement: blackbox:9115
