
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

rule_files:
- /etc/prometheus/alerts/*.yml

alerting:
  alertmanagers:
  - scheme: http
    timeout: 10s
    api_version: v2
    basic_auth:
      username: admin
      password: admin
    static_configs:
    - targets:
      - fromedwin_alertmanager:9093

scrape_configs:

# Prometheus metrics
- job_name: prometheus_metrics
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090

# Alertmanager metrics
- job_name: alertmanager_metrics
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  basic_auth:
    username: admin
    password: admin
  static_configs:
  - targets:
    - alertmanager:9093

    
# Parse http probe for service WITH TLS SECURE VERIFICATION
- job_name: is_service_down
  metrics_path: /probe
  scrape_interval: 60s
  params:
    module:
    - http_2xx
  relabel_configs:
  - source_labels:
    - __address__
    target_label: __param_target
  - source_labels:
    - __param_target
    target_label: instance
  - target_label: __address__
    replacement: fromedwin_blackbox:9115

# Parse http probe for service WITHOUT TLS SECURE VERIFICATION
- job_name: is_service_down_and_insecure
  metrics_path: /probe
  scrape_interval: 60s
  params:
    module:
    - http_2xx_unsecure
  static_configs:
  
  relabel_configs:
  - source_labels:
    - __address__
    target_label: __param_target
  - source_labels:
    - __param_target
    target_label: instance
  - target_label: __address__
    replacement: fromedwin_blackbox:9115
