
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

rule_files:
- /etc/prometheus/alerts/*.yml

alerting:
  alertmanagers:
  - scheme: http
    timeout: 10s
    api_version: v2
    
    static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:

# Prometheus metrics
- job_name: prometheus_metrics
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090

# Alertmanager metrics
- job_name: alertmanager_metrics
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  
  static_configs:
  - targets:
    - alertmanager:9093

    
# Parse http probe for service WITH TLS SECURE VERIFICATION
- job_name: is_service_down
  metrics_path: /probe
  scrape_interval: 60s
  params:
    module:
    - http_2xx
  static_configs:
  
  - labels:
      service: 13
      project: 19
      user: 1
    targets:
    - https://unique.ai
    
  - labels:
      service: 14
      project: 20
      user: 1
    targets:
    - https://sebastienbarbier.com
    
  - labels:
      service: 15
      project: 21
      user: 1
    targets:
    - https://www.irinabarbos.com
    
  relabel_configs:
  - source_labels:
    - __address__
    target_label: __param_target
  - source_labels:
    - __param_target
    target_label: instance
  - target_label: __address__
    replacement: blackbox:9115

# Parse http probe for service WITHOUT TLS SECURE VERIFICATION
- job_name: is_service_down_and_insecure
  metrics_path: /probe
  scrape_interval: 60s
  params:
    module:
    - http_2xx_unsecure
  static_configs:
  
  relabel_configs:
  - source_labels:
    - __address__
    target_label: __param_target
  - source_labels:
    - __param_target
    target_label: instance
  - target_label: __address__
    replacement: blackbox:9115

remote_write:
 - url: "http://worker_telegraf:1234/receive"
   write_relabel_configs:
     # Keep only specific metrics by name
     - source_labels: ["__name__"]
       regex: "probe_dns_lookup_time_seconds|probe_success|probe_ssl_last_chain_info|probe_ssl_last_chain_expiry_timestamp_seconds|probe_ssl_earliest_cert_expiry|probe_ip_addr_hash|probe_ip_protocol|probe_http_version|probe_http_uncompressed_body_length|probe_http_status_code|probe_http_ssl|probe_http_redirects|probe_http_last_modified_timestamp_seconds|probe_http_duration_seconds|probe_http_content_length|probe_failed_due_to_regex|probe_duration_seconds|probe_tls_version_info"
       action: keep
