# Generated by Django 3.1.4 on 2021-03-24 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(choices=[(200, '200 - OK'), (404, '404 - Not Found'), (418, '418 - I’m a teapot'), (500, '500 - Internal Server Error')])),
                ('comment', models.CharField(blank=True, help_text='Max 258 characters', max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='healthTest', related_query_name='', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
