# Generated by Django 3.1.4 on 2021-03-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthtest',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='healthtest',
            name='code',
            field=models.IntegerField(choices=[(200, '200 - OK'), (404, '404 - Not Found'), (418, '418 - I’m a teapot'), (500, '500 - Internal Server Error')]),
        ),
    ]
