# Generated by Django 3.2.7 on 2021-11-03 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20211020_1147'),
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthtest',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='healthTest', related_query_name='', to='projects.service'),
        ),
    ]
