# Generated by Django 3.1.4 on 2021-03-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_auto_20210322_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthtest',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
