# Generated by Django 3.1.4 on 2021-03-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_auto_20210322_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthtest',
            name='comment',
            field=models.CharField(blank=True, help_text='Max 258 characters', max_length=256),
        ),
    ]
