# Generated by Django 5.1.3 on 2024-11-27 06:17

import django.db.models.deletion
import django.utils.timezone
import projects.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('url', models.URLField(blank=True, help_text="Application's URL", max_length=512, null=True)),
                ('is_favorite', models.BooleanField(default=False, help_text='Favorite project are highlighted and first shown when possible.', verbose_name='Is favorite')),
                ('enable_public_page', models.BooleanField(default=False, help_text='Will enable the public page to share current project status', verbose_name='Enable public page')),
                ('favicon', models.ImageField(blank=True, help_text="Application's favicon", null=True, upload_to=projects.models.project_favicon_path)),
                ('favicon_task_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', help_text='Favicon task status', max_length=16)),
                ('favicon_last_edited', models.DateTimeField(default=django.utils.timezone.now, help_text='Last time favicon was edited')),
                ('sitemap_task_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', help_text='Sitemap task status', max_length=16)),
                ('sitemap_last_edited', models.DateTimeField(default=django.utils.timezone.now, help_text='Last time sitemap was edited')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='URL to monitor', max_length=512)),
                ('title', models.CharField(blank=True, help_text='Page title', max_length=128)),
                ('description', models.TextField(blank=True, help_text='Page description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sitemap_last_seen', models.DateTimeField(blank=True, help_text='Last time sitemap was reported', null=True)),
                ('scraping_last_seen', models.DateTimeField(blank=True, help_text='Last time scraping was run', null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='projects.project')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'url'), name='unique_page_project_url')],
            },
        ),
    ]
