# Generated by Django 4.2.13 on 2024-10-09 09:27

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Lighthouse report', null=True, upload_to=projects.models.project_favicon_path),
        ),
    ]
