# Generated by Django 4.2 on 2025-07-09 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_pages_project"),
        ("favicons", "0002_auto_20250709_2012"),  # Ensure data migration is complete
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='favicon',
        ),
        migrations.RemoveField(
            model_name='project',
            name='favicon_task_status',
        ),
        migrations.RemoveField(
            model_name='project',
            name='favicon_last_edited',
        ),
    ]
