# Generated by Django 4.2.13 on 2024-10-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, help_text="Application's URL", max_length=512, null=True),
        ),
    ]
