# Generated by Django 4.2 on 2025-07-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_auto_20250709_2012"),
    ]

    operations = [
        migrations.AddField(
            model_name="pages",
            name="lighthouse_last_request",
            field=models.DateTimeField(
                blank=True, help_text="Last time lighthouse was requested", null=True
            ),
        ),
    ]
