# Generated by Django 4.2 on 2025-07-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_pages_lighthouse_last_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="pages",
            name="http_status",
            field=models.IntegerField(
                blank=True, help_text="HTTP status of the page", null=True
            ),
        ),
    ]
