# Generated by Django 4.2.13 on 2024-10-11 10:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='favicon_last_edited',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Last time favicon was edited'),
        ),
        migrations.AddField(
            model_name='project',
            name='favicon_task_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', help_text='Favicon task status', max_length=16),
        ),
    ]
