# Generated by Django 4.2 on 2024-10-17 08:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_favicon_last_edited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sitemap_last_edited',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Last time sitemap was edited'),
        ),
        migrations.AddField(
            model_name='project',
            name='sitemap_task_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', help_text='Sitemap task status', max_length=16),
        ),
        migrations.AlterField(
            model_name='project',
            name='favicon_last_edited',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Last time favicon was edited'),
        ),
    ]
