# Generated by Django 4.2 on 2025-07-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_pages_http_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pages",
            name="description",
            field=models.TextField(blank=True, help_text="Page description", null=True),
        ),
    ]
