# Generated by Django 4.2 on 2025-07-23 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_alter_pages_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this link was first discovered",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this link was last seen"
                    ),
                ),
                (
                    "from_page",
                    models.ForeignKey(
                        help_text="The page that contains the link",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outbound_links",
                        to="projects.pages",
                    ),
                ),
                (
                    "to_page",
                    models.ForeignKey(
                        help_text="The page that is being linked to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inbound_links",
                        to="projects.pages",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="pagelink",
            index=models.Index(
                fields=["from_page"], name="projects_pa_from_pa_a4314e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pagelink",
            index=models.Index(
                fields=["to_page"], name="projects_pa_to_page_b18ac7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="pagelink",
            constraint=models.UniqueConstraint(
                fields=("from_page", "to_page"), name="unique_page_link"
            ),
        ),
    ]
