# Generated by Django 4.2 on 2025-08-03 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0001_initial"),
        ("projects", "0007_add_pagelink_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="pages",
            name="scraping_task_log",
            field=models.ForeignKey(
                blank=True,
                help_text="Celery task log associated with this scraping task report",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="page",
                to="logs.celerytasklog",
            ),
        ),
    ]
