# Generated by Django 3.1.4 on 2021-03-23 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, help_text='Creation date')),
                ('json', models.TextField(help_text='RAW json as received by the webhook')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', related_query_name='alert', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
