# Generated by Django 3.1.4 on 2021-03-24 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('json', models.TextField(help_text='RAW json as received by the webhook')),
            ],
            options={
                'verbose_name': 'Unknown alert',
                'verbose_name_plural': 'Unknown alerts',
            },
        ),
        migrations.CreateModel(
            name='InstanceDownAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('json', models.TextField(help_text='RAW json as received by the webhook')),
                ('status', models.IntegerField(choices=[(0, 'unknown'), (1, 'resolved'), (2, 'firing')])),
                ('severity', models.IntegerField(choices=[(0, 'unknown'), (1, 'warning'), (2, 'critical')])),
                ('startsAt', models.DateTimeField()),
                ('endsAt', models.DateTimeField(blank=True, null=True)),
                ('instance', models.TextField(null=True)),
                ('summary', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', related_query_name='alert', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instance down alert',
                'verbose_name_plural': 'Instance down alerts',
            },
        ),
    ]
