# Generated by Django 3.1.4 on 2021-03-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericalert',
            name='fingerprint',
            field=models.CharField(default='abc', editable=False, help_text='Fingerprint provided by prometheus', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instancedownalert',
            name='fingerprint',
            field=models.CharField(default='abc', editable=False, help_text='Fingerprint provided by prometheus', max_length=128),
            preserve_default=False,
        ),
    ]
