# Generated by Django 3.2.7 on 2021-09-22 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alerts', '0002_auto_20210324_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericalert',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genericalerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='instancedownalert',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instancedownalerts', to=settings.AUTH_USER_MODEL),
        ),
    ]
