# Generated by Django 3.1.4 on 2021-03-23 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alerts', '0002_auto_20210323_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('json', models.TextField(help_text='RAW json as received by the webhook')),
            ],
        ),
        migrations.CreateModel(
            name='InstanceDownAlert',
            fields=[
                ('genericalert_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='alerts.genericalert')),
                ('status', models.IntegerField(choices=[(0, 'resolved'), (1, 'firing')])),
                ('severity', models.IntegerField(choices=[(0, 'warning'), (1, 'critical')])),
                ('startsAt', models.DateTimeField()),
                ('endsAt', models.DateTimeField(null=True)),
                ('instance', models.TextField(null=True)),
                ('summary', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', related_query_name='alert', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('alerts.genericalert',),
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
    ]
