# Generated by Django 3.2.7 on 2021-10-06 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_delete_notify_pager_duty'),
        ('alerts', '0003_auto_20210922_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instancedownalert',
            name='user',
        ),
        migrations.AddField(
            model_name='instancedownalert',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instancedownalerts', to='applications.service'),
        ),
        migrations.CreateModel(
            name='ApplicationAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('json', models.TextField(help_text='RAW json as received by the webhook')),
                ('fingerprint', models.CharField(editable=False, help_text='Fingerprint provided by prometheus', max_length=128)),
                ('status', models.IntegerField(choices=[(0, 'unknown'), (1, 'resolved'), (2, 'firing')])),
                ('severity', models.IntegerField(choices=[(0, 'unknown'), (1, 'warning'), (2, 'critical')])),
                ('startsAt', models.DateTimeField()),
                ('endsAt', models.DateTimeField(blank=True, null=True)),
                ('instance', models.TextField(null=True)),
                ('summary', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicationalerts', to='applications.application')),
            ],
            options={
                'verbose_name': 'Application alert',
                'verbose_name_plural': 'Application alerts',
            },
        ),
    ]
