# Generated by Django 3.1.4 on 2021-03-23 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_auto_20210323_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genericalert',
            old_name='date',
            new_name='creation_date',
        ),
    ]
