# Generated by Django 3.1.4 on 2021-03-24 21:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_auto_20210323_2228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genericalert',
            options={'verbose_name': 'Unknown alert', 'verbose_name_plural': 'Unknown alerts'},
        ),
        migrations.AlterModelOptions(
            name='instancedownalert',
            options={'verbose_name': 'Instance down alert', 'verbose_name_plural': 'Instance down alerts'},
        ),
        migrations.RemoveField(
            model_name='instancedownalert',
            name='genericalert_ptr',
        ),
        migrations.AddField(
            model_name='instancedownalert',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instancedownalert',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instancedownalert',
            name='json',
            field=models.TextField(default={}, help_text='RAW json as received by the webhook'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instancedownalert',
            name='endsAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instancedownalert',
            name='severity',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'warning'), (2, 'critical')]),
        ),
        migrations.AlterField(
            model_name='instancedownalert',
            name='status',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'resolved'), (2, 'firing')]),
        ),
    ]
