# Generated by Django 4.1.5 on 2023-08-16 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('is_public', models.BooleanField(default=True, help_text='Service will appears on application status board', verbose_name='Is visible')),
                ('is_enabled', models.BooleanField(default=True, help_text='Disabled service will not be monitored')),
                ('is_critical', models.BooleanField(default=True, help_text='Application is offline if this service fail, otherwise will only report as degraded')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='HTTPMockedCodeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(choices=[(200, '200 - OK'), (404, '404 - Not Found'), (418, '418 - I’m a teapot'), (500, '500 - Internal Server Error')])),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='httpmockedcode', to='availability.service')),
            ],
        ),
        migrations.CreateModel(
            name='HTTPCodeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=512)),
                ('tls_skip_verify', models.BooleanField(default=False, help_text='Might be needed for monitoring some CDN or object storage directly.', verbose_name='Ignore unsecure SSL')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='httpcode', to='availability.service')),
            ],
        ),
    ]
