# Generated by Django 4.1.5 on 2023-03-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0005_alter_httpcodeservice_tls_skip_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='httpcodeservice',
            name='tls_skip_verify',
            field=models.BooleanField(default=False, help_text='Might be needed for monitoring some CDN or object storage directly.', verbose_name='Ignore unsecure SSL'),
        ),
    ]
