# Generated by Django 4.1.5 on 2023-08-02 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_emails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pager_Duty',
        ),
    ]
