# Generated by Django 4.1.5 on 2023-08-16 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('availability', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectIncident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance', models.TextField(null=True)),
                ('summary', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('startsAt', models.DateTimeField()),
                ('endsAt', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'unknown'), (1, 'resolved'), (2, 'firing')])),
                ('severity', models.IntegerField(choices=[(0, 'unknown'), (1, 'warning'), (2, 'critical')])),
                ('fingerprint', models.CharField(editable=False, help_text='Fingerprint provided by prometheus', max_length=128)),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('json', models.TextField(help_text='RAW json as received by the webhook')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectincident', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project alert',
                'verbose_name_plural': 'Project alerts',
            },
        ),
        migrations.CreateModel(
            name='InstanceDownIncident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance', models.TextField(null=True)),
                ('summary', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('startsAt', models.DateTimeField()),
                ('endsAt', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'unknown'), (1, 'resolved'), (2, 'firing')])),
                ('severity', models.IntegerField(choices=[(0, 'unknown'), (1, 'warning'), (2, 'critical')])),
                ('fingerprint', models.CharField(editable=False, help_text='Fingerprint provided by prometheus', max_length=128)),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('json', models.TextField(help_text='RAW json as received by the webhook')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instancedownincidents', to='availability.service')),
            ],
            options={
                'verbose_name': 'Service down incident',
                'verbose_name_plural': 'Service down incidents',
            },
        ),
        migrations.CreateModel(
            name='GenericIncident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance', models.TextField(null=True)),
                ('summary', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('startsAt', models.DateTimeField()),
                ('endsAt', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'unknown'), (1, 'resolved'), (2, 'firing')])),
                ('severity', models.IntegerField(choices=[(0, 'unknown'), (1, 'warning'), (2, 'critical')])),
                ('fingerprint', models.CharField(editable=False, help_text='Fingerprint provided by prometheus', max_length=128)),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('json', models.TextField(help_text='RAW json as received by the webhook')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genericincidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unknown alert',
                'verbose_name_plural': 'Unknown alerts',
            },
        ),
    ]
