# Generated by Django 4.1.5 on 2023-09-04 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0001_initial'),
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unknownincident',
            name='incident',
        ),
        migrations.AddField(
            model_name='incident',
            name='alert_name',
            field=models.CharField(default='', help_text='Alert name', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='availability.service'),
        ),
        migrations.AddField(
            model_name='incident',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='ServiceIncident',
        ),
        migrations.DeleteModel(
            name='UnknownIncident',
        ),
    ]
