# Generated by Django 4.1.5 on 2023-08-21 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0001_initial'),
        ('alerts', '0009_alter_disablealerts_alert_and_more'),
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'unknown'), (1, 'resolved'), (2, 'firing')])),
                ('severity', models.IntegerField(choices=[(0, 'unknown'), (1, 'warning'), (2, 'critical')])),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('json', models.TextField(help_text='RAW json as received by the webhook')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceIncident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_incidents', to='alerts.alerts')),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_incidents', to='incidents.incident')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='availability.service')),
            ],
        ),
        migrations.CreateModel(
            name='UnknownIncident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_name', models.CharField(help_text='Alert name', max_length=128, unique=True)),
                ('summary', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unknown_incidents', to='incidents.incident')),
            ],
        ),
        migrations.RemoveField(
            model_name='instancedownincident',
            name='service',
        ),
        migrations.RemoveField(
            model_name='projectincident',
            name='project',
        ),
        migrations.DeleteModel(
            name='GenericIncident',
        ),
        migrations.DeleteModel(
            name='InstanceDownIncident',
        ),
        migrations.DeleteModel(
            name='ProjectIncident',
        ),
    ]
