# Generated by Django 4.1.5 on 2023-08-16 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alerts',
        ),
    ]
