# Generated by Django 4.1.5 on 2023-02-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics',
            name='url',
            field=models.URLField(help_text='No tailing slash, or will break prometheus config file', max_length=512),
        ),
    ]
