# Generated by Django 4.1.5 on 2023-08-16 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_delete_alerts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metrics',
            options={'verbose_name': 'Metric', 'verbose_name_plural': 'Metrics'},
        ),
    ]
