# Generated by Django 4.1.5 on 2023-07-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_server_lighthouse_server_prometheus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='lighthouse',
            new_name='performance',
        ),
        migrations.RemoveField(
            model_name='server',
            name='prometheus',
        ),
        migrations.AddField(
            model_name='server',
            name='monitoring',
            field=models.BooleanField(default=False),
        ),
    ]
