# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = 'FromEdwin'
copyright = '2025, Sébastien Barbier'
author = 'Sébastien Barbier'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
	'myst_parser',
	'sphinx_rtd_theme',
    'sphinxcontrib.mermaid',
    'sphinx.ext.autodoc',
    'sphinx.ext.viewcode',
    'sphinx.ext.napoleon',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# -- MyST Parser Configuration -----------------------------------------------

# Enable additional MyST features for better documentation
myst_enable_extensions = [
    "colon_fence",
    "deflist",
    "html_image",
    "linkify",
    "replacements",
    "smartquotes",
    "substitution",
    "tasklist",
]

# -- Code highlighting -------------------------------------------------------

# The default language to highlight source code in
highlight_language = 'python'

# Pygments style for syntax highlighting
pygments_style = 'default'


html_theme_options = {
    'collapse_navigation': False,  # Keeps the navigation expanded
    'navigation_depth': 2,         # Allows up to 3 levels for better settings documentation
    'sticky_navigation': True,     # Make navigation sticky
    'includehidden': True,         # Include hidden toctrees
    'titles_only': False,          # Show full titles in navigation
    'style_external_links': True,  # Style external links differently
}
# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '0.11'
# The full version, including alpha/beta/rc tags.
release = '0.11.0'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# -- Settings Documentation Support ------------------------------------------

# Add custom CSS for better code blocks and admonitions
html_css_files = [
    'custom.css',
]

# Add source file suffix for better linking
source_suffix = {
    '.rst': None,
    '.md': 'myst_parser',
}

# Add warning for missing references
nitpicky = True

