# Define the keys and default values for timing settings
TIMING_KEYS = [
    'BEAT_SCHEDULE_INTERVAL_SECONDS',
    'REPORT_INTERVAL_DAYS',
    'LIGHTHOUSE_INTERVAL_HOURS',
    'SITEMAP_INTERVAL_HOURS',
    'FAVICON_INTERVAL_HOURS',
]

# SLOW timings
SLOW = {
    'BEAT_SCHEDULE_INTERVAL_SECONDS': 60,
    'REPORT_INTERVAL_DAYS': 7,
    'LIGHTHOUSE_INTERVAL_HOURS': 24,
    'SITEMAP_INTERVAL_HOURS': 24,
    'FAVICON_INTERVAL_HOURS': 6,
}

# FAST timings
FAST = {
    'BEAT_SCHEDULE_INTERVAL_SECONDS': 10,
    'REPORT_INTERVAL_DAYS': 1,
    'LIGHTHOUSE_INTERVAL_HOURS': 1,
    'SITEMAP_INTERVAL_HOURS': 1,
    'FAVICON_INTERVAL_HOURS': 1,
}

DEV = FAST;
PRODUCTION = SLOW;