# Generated by Django 3.2.10 on 2022-01-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_enable_public_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='Is define as favorite project'),
        ),
    ]
