# Generated by Django 3.2.7 on 2021-10-06 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_delete_notify_pager_duty'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 10, 6, 12, 41, 42, 180528), help_text='Creation date'),
            preserve_default=False,
        ),
    ]
