# Generated by Django 3.2.7 on 2021-10-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_service_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrics',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='is_critical',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
