# Generated by Django 3.2.7 on 2021-11-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20211020_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='is_critical',
            field=models.BooleanField(default=True, help_text='Application is offline if this service fail, otherwise will only report as degraded'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='Disabled service will not be monitored'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Service will appears on application status board', verbose_name='Is visible'),
        ),
    ]
